version: '3.8'
services:
  ecomm-mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-v:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    security_opt:
      - seccomp:unconfined
    networks:
      - ecomm-network
  ecomm-main:
    image: openjdk:17-alpine
    depends_on:
      - ecomm-mysql
    working_dir: /work
    volumes:
      - ./:/work
    # Change to "./mvnw install -DskipTests" to skip tests
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "./mvnw dependency:go-offline --no-transfer-progress && ./mvnw install --no-transfer-progress -DskipTests && java
          -jar target/app.jar"
      ]
    ports:
      - 8080:8080
    # restart: on-failure
    environment:
      - DATABASE_HOST=ecomm-mysql
      - DATABASE_USER=springuser
      - DATABASE_PASSWORD=MySQL-P
      - DATABASE_NAME=jokr_db
      - DATABASE_PORT=3306
    networks:
      - ecomm-network
  ecomm-front:
    image: pacodevs/jokr-front:latest
    depends_on:
      - ecomm-main
    ports:
      - 3000:3000
    networks:
      - ecomm-network
networks:
  ecomm-network: null
volumes:
  mysql-v:
    external: false
